# --- Configuration Storage Engines ---
function Read-Config {
  <#
    .SYNOPSIS
      Loads PSD1 Configuration file.
    .PARAMETER ConfigPath
      Path to the config file
  #>
  param([string]$ConfigPath)
  if (Test-Path $ConfigPath) {
    try {
      # Import data file, forcing syntax
      $data = Import-PowerShellDataFile -Path $ConfigPath -ErrorAction Stop

      if ($null -eq $data) { throw "The configuration file is empty."}

      # Converting raw hashtables into rich PSCustomObjects so dot-notation works elsewhere.
      $cleanCalendars = @(foreach ($c in $data.Calendars) { [PSCustomObject]$c })
      $cleanGroups    = @(foreach ($g in $data.Groups) { [PSCustomObject]$g })

      return [PSCustomObject]@{
        Calendars  = $cleanCalendars
        Groups     = $cleanGroups
      }
    } catch {
      throw "Configuration parsing failed. The file may contain a syntax error. Details: $($_.Exception.Message)"
    }

  }
    # Return default structural blueprint if missing
  return @{
    Calendars  = @()
    Groups     = @()
  }
}

function Save-Config {
    <#
    .SYNOPSIS
        Saves formatted config data to .psd1 file
    .PARAMETER ConfigPath
        File location
    .PARAMETER ConfigData
        Data
    .PARAMETER Operation
      Describes the operation (optional, defaults to "Configuration")
    #>
    param(
        [string]$ConfigPath,
        [PSCustomObject]$ConfigData,
        [string]$Operation = "Configuration"
    )

    function Format-PSD1Value {
        param($InputData, $IndentLevel = 0)

        $basePadding  = " " * ($IndentLevel * 4)
        $innerPadding = " " * (($IndentLevel + 1) * 4)

        if ($InputData -is [System.Management.Automation.PSCustomObject]) {
          $properties = $InputData.PSObject.Properties
          if ($properties.Count -eq 0) { return "@{}"}

          $lines = [System.Collections.Generic.List[string]]::new()
          $lines.Add("@{")
          foreach ($prop in $properties) {
            $valStr = Format-PSD1Value -InputData $prop.Value -IndentLevel ($IndentLevel +1)
            $lines.Add("${innerPadding}$($prop.Name) = $valStr")
          }
          $lines.Add("${basePadding}}")
          return $lines -join "`n"
        }
        # Native hashtables / mapped dictionaries
        elseif ($InputData -is [Hashtable] -or $InputData -is [System.Collections.IDictionary]) {
            if ($InputData.Count -eq 0) { return "@{}" }

            $lines = [System.Collections.Generic.List[string]]::new()
            $lines.Add("@{")
            foreach ($key in $InputData.Keys) {
                $valStr = Format-PSD1Value -InputData $InputData[$key] -IndentLevel ($IndentLevel + 1)
                $lines.Add("${innerPadding}$key = $valStr")
            }
            $lines.Add("${basePadding}}")
            return $lines -join "`n"
        }
        # Arrays / group lists
        elseif ($InputData -is [Array] -or $InputData -is [System.Collections.IList]) {
            if ($InputData.Count -eq 0) { return "@()" }

            $lines = [System.Collections.Generic.List[string]]::new()
            $lines.Add("@(")
            foreach ($item in $InputData) {
                $valStr = Format-PSD1Value -InputData $item -IndentLevel ($IndentLevel + 1)
                $lines.Add("${innerPadding}${valStr},")
            }

            $lastIndex = $lines.Count - 1
            $lines[$lastIndex] = $lines[$lastIndex] -replace ',\s*$', ''

            $lines.Add("${basePadding})")
            return $lines -join "`n"
        }
        elseif ($InputData -is [String]) {
            return "'$($InputData -replace "'", "''")'"
        }
        elseif ($null -eq $InputData) {
            return '$null'
        }
        elseif ($InputData -is [bool]) {
            return '$' + $InputData.ToString().ToLower()
        }
        else {
            return $InputData.ToString()
        }
    }

    # Generate layout structure
    $Content = Format-PSD1Value -InputData $ConfigData -IndentLevel 0

    $header = @"
# This file is automatically generated by the TUI Management Engine.
# Manual modifications are supported but comments may be overwritten.
"@

    # Write out file clean without inherited script block tab strings
    "$header`n$Content" | Out-File -FilePath $ConfigPath -Encoding utf8 -Force
    Write-Host "`n$Operation written to: $ConfigPath" -ForegroundColor Green
    Start-Sleep -Seconds 2
}

# --- STATE MANAGEMENT ---
function Read-State {
  <#
    .SYNOPSIS
      Gets information from the state file
    .PARAMETER StateDir
      Directory location for state file
    .PARAMETER GroupEmail
      Expects string; Should be a Google Group Email address
  #>
  param([string]$StateDir, [string]$GroupEmail)
    $stateFile = Join-Path $StateDir "state-$($GroupEmail -replace '[^a-zA-Z0-9]', '-').json"
    if (Test-Path $stateFile) {
        return Get-Content $stateFile | ConvertFrom-Json
    }
    # No state file yet - return empty object
    return [PSCustomObject]@{}
}

function Save-State {
  <#
    .SYNOPSIS
      Creates/Saves the state file
    .DESCRIPTION
      Each group has their own JSON state file, labeled state-<GroupEmail>.
    .PARAMETER StateDir
      Directory location for state file
    .PARAMETER GroupEmail
      Expects a string; Should be a Google Group Email address
  #>
  param([string]$StateDir, [string]$GroupEmail, [PSCustomObject]$State)
    if (-not (Test-Path $StateDir)) {
        New-Item -ItemType Directory -Path $StateDir -Force | Out-Null
    }
    $stateFile = Join-Path $StateDir "state-$($GroupEmail -replace '[^a-zA-Z0-9]', '-').json"
    $State | ConvertTo-Json -Depth 10 | Out-File $stateFile
}

function Update-SubscriptionState {
  <#
    .SYNOPSIS
      Stamps each subscribed user with the current datetime for this calendar.
  #>
  param(
    [PSCustomObject]$State,
    [string]$CalendarId,
    [array]$SubscribedUsers
  )
  if (-not $State.$CalendarId) {
    $State | Add-Member -NotePropertyName $CalendarId -NotePropertyValue ([PSCustomObject]@{}) -Force
  }
  $now = (Get-Date).ToString("o") # ISO 8601
  foreach ($user in $SubscribedUsers) {
    # Ensure we add the email as a property to the calendar sub-object
    if (-not $State.$CalendarId.$($user.email)) {
        $State.$CalendarId | Add-Member -NotePropertyName $user.email -NotePropertyValue $now -Force
    } else {
        $State.$CalendarId.$($user.email) = $now
    }
  }
  return $State
}

# --- CALCULATE DELTAS ---
function Get-UsersNeedingSubscription {
  <#
    .SYNOPSIS
      Returns users from $Members who have no state entry for this calendar
    .PARAMETER Members
      Expects an array; Should be email addresses
    .PARAMETER CalendarId
      Expects a string; Should be a Google Calendar ID
  #>
  param(
      [array]$Members,
      [PSCustomObject]$State,
      [string]$CalendarId
  )
  $calState = $State.$CalendarId

  return $Members | Where-Object {
      $email    = $_.email
      # If the user is in the state file, they had been subscribed!
      $Subscribed = if ($calState -and $calState.$email) { $true } else { $false }
      -not $Subscribed
  }
}

# Export functions explicitly to scope them for external calls
Export-ModuleMember -Function Read-Config, Save-Config, Read-State, Save-State, Update-SubscriptionState, Get-UsersNeedingSubscription