# This file is automatically generated by the TUI Management Engine.
# Manual modifications are supported but comments may be overwritten.
@{
    Calendars = @(
        @{
            Label = 'aaa'
            Id = 'aaa'
        },
        @{
            Label = 'cra'
            Id = 'crap'
        }
    )
    Groups = @(
        @{
            CalendarIds = @(
                'aaa',
                'crap'
            )
            Email = 'boop'
            Label = 'boop'
        },
        @{
            CalendarIds = @(
                'crap'
            )
            Email = 'booty@every.where'
            Label = 'shakin'
        }
    )
}
